version: "3.9"

services:

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: repair
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  soap-server:
    build:
      context: ..
      dockerfile: soap_projekt/src/server/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: repair
      DB_USER: admin
      DB_PASSWORD: admin

volumes:
  db_data: